name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    
    - name: install valgrind and splint
      run: 
         sudo apt install valgrind
         sudo apt splint
    - uses: actions/checkout@v2
    - name: Make
      run: 
        make -C LabC/lab7/ 
    - name: Upload
      uses: codecov/codecov-action@v1
      with: 
          token: ${{ secrets.CODECOV_TOKEN }} 884e416a-e9a4-4999-bfaa-cdbcecaa34bb
          files: |
            LabC/lab7/DataClient.cpp.gcov
